# EXECUTE THOSE CONTAINERS ON THE SERVER THAT WILL RUN GRAFANA (PREFERABLY, ON A DIFFERENT SERVER FROM YOUR APP)
version: '3'
services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    ports:
      - 9091:9091
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - $PWD/grafana:/var/lib/grafana
    user: root
